[package]
name = "rawrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawloader = {path="../rawloader"} 
image = "0.24"
byteorder = "1.4"

[profile.release]
debug = true